[
   {
      "title":"lp24-06-03",
      "data":{
         "b0633072-f939-4fbe-a4a0-ea602729cf82":{
            "37e1ab4e-d35f-4266-952e-fa7648e7b342":{
               "AT":"https://www.beliani.at/",
               "CHDE":"https://www.beliani.ch/",
               "CHFR":"https://www.beliani.ch/",
               "CZ":"https://www.beliani.cz/",
               "DE":"https://www.beliani.de/",
               "DK":"https://www.beliani.dk/",
               "ES":"https://www.beliani.es/",
               "FI":"https://www.beliani.fi/",
               "FR":"https://www.beliani.fr/",
               "HU":"https://www.beliani.hu/",
               "IT":"https://www.beliani.it/",
               "NL":"https://www.beliani.nl/",
               "NO":"https://www.beliani.no/",
               "PL":"https://www.beliani.pl/",
               "PT":"https://www.beliani.pt/",
               "SE":"https://www.beliani.se/",
               "SK":"https://www.beliani.sk/",
               "UK":"https://www.beliani.co.uk/"
            },
            "c45861e7-52f3-44c3-ad40-66a0b23ab9d5":{
               "AT":"https://upload.pictureserver.net/static/2024/at20240524_01.jpg",
               "CHDE":"https://upload.pictureserver.net/static/2024/chde20240524_01.jpg",
               "CHFR":"https://upload.pictureserver.net/static/2024/chfr20240524_01.jpg",
               "CZ":"https://upload.pictureserver.net/static/2024/cz20240524_01.jpg",
               "DE":"https://upload.pictureserver.net/static/2024/de20240524_01.jpg",
               "DK":"https://upload.pictureserver.net/static/2024/dk20240524_01.jpg",
               "ES":"https://upload.pictureserver.net/static/2024/es20240524_01.jpg",
               "FI":"https://upload.pictureserver.net/static/2024/fi20240524_01.jpg",
               "FR":"https://upload.pictureserver.net/static/2024/fr20240524_01.jpg",
               "HU":"https://upload.pictureserver.net/static/2024/hu20240524_01.jpg",
               "IT":"https://upload.pictureserver.net/static/2024/it20240524_01.jpg",
               "NL":"https://upload.pictureserver.net/static/2024/nl20240524_01.jpg",
               "NO":"https://upload.pictureserver.net/static/2024/no20240524_01.jpg",
               "PL":"https://upload.pictureserver.net/static/2024/pl20240524_01.jpg",
               "PT":"https://upload.pictureserver.net/static/2024/pt20240524_01.jpg",
               "SE":"https://upload.pictureserver.net/static/2024/se20240524_01.jpg",
               "SK":"https://upload.pictureserver.net/static/2024/sk20240524_01.jpg",
               "UK":"https://upload.pictureserver.net/static/2024/uk20240524_01.jpg"
            },
            "2ff5c8d1-677d-45c9-ba91-fcedb356a884":{
               "AT":"https://www.beliani.ch/",
               "CHDE":"https://www.beliani.ch/",
               "CHFR":"https://www.beliani.ch/",
               "CZ":"https://www.beliani.ch/",
               "DE":"https://www.beliani.ch/",
               "DK":"https://www.beliani.ch/",
               "ES":"https://www.beliani.ch/",
               "FI":"https://www.beliani.ch/",
               "FR":"https://www.beliani.ch/",
               "HU":"https://www.beliani.ch/",
               "IT":"https://www.beliani.ch/",
               "NL":"https://www.beliani.ch/",
               "NO":"https://www.beliani.ch/",
               "PL":"https://www.beliani.ch/",
               "PT":"https://www.beliani.ch/",
               "SE":"https://www.beliani.ch/",
               "SK":"https://www.beliani.ch/",
               "UK":"https://www.beliani.ch/"
            },
            "f2e9f03b-2a6a-4c20-a629-be11d0df1623":{
               "AT":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "CHDE":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "CHFR":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "CZ":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "DE":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "DK":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "ES":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "FI":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "FR":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "HU":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "IT":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "NL":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "NO":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "PL":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "PT":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "SE":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "SK":"https://upload.pictureserver.net/static/2024/20240524gif.gif",
               "UK":"https://upload.pictureserver.net/static/2024/20240524gif.gif"
            }
         },
         "22281359-e66b-4fbf-b1ce-678baa9765f0":{
            "4ea37ff7-e3fc-46e0-8ab7-3815ebdfb76a":{
               "AT":"Extra 5% Rabatt auf alles",
               "CHDE":"Extra 5% Rabatt auf alles",
               "CHFR":"5% de réduction supplémentaire sur tout",
               "CZ":"Extra sleva 5 % na vše",
               "DE":"Extra 5% Rabatt auf alles",
               "DK":"Ekstra 5% rabat på alt",
               "ES":"5% de descuento adicional",
               "FI":"Saa 5% lisäalennus kaikesta ",
               "FR":"5% de réduction supplémentaire sur tout",
               "HU":"További 5% kedvezményt adunk",
               "IT":"5% di Sconto Aggiuntivo",
               "NL":"Extra 5% Rabatt auf alles",
               "NO":"Ytterligere 5% rabatt på alt",
               "PL":"Dodatkowe 5% rabatu ",
               "PT":"5% de desconto adicional",
               "SE":"Ytterligare 5% rabatt på allt",
               "SK":"Extra zľava 5 % na všetko",
               "UK":"Additional 5% off everything"
            },
            "42ae756c-6473-445e-bad5-7e91a4298f18":{
               "AT":"Extra 10% Rabatt auf alles",
               "CHDE":"Extra 10% Rabatt auf alles",
               "CHFR":"10% de réduction supplémentaire sur tout",
               "CZ":"Extra sleva 10 % na vše",
               "DE":"Extra 10% Rabatt auf alles",
               "DK":"Ekstra 10% rabat på alt",
               "ES":"10% de descuento adicional",
               "FI":"Saa 10% lisäalennus kaikesta ",
               "FR":"10% de réduction supplémentaire sur tout",
               "HU":"További 10% kedvezményt adunk",
               "IT":"10% di Sconto Aggiuntivo",
               "NL":"Krijg 10% extra korting op alles",
               "NO":"Ytterligere 10% rabatt på alt",
               "PL":"Dodatkowe 10% rabatu ",
               "PT":"10% de desconto adicional",
               "SE":"Ytterligare 10% rabatt på allt",
               "SK":"Extra zľava 10 % na všetko",
               "UK":"Additional 10% off everything "
            },
            "5788b45a-3d7b-4d1a-b6ba-7e4adbd78fc4":{
               "AT":"Extra 15% Rabatt auf alles",
               "CHDE":"Extra 15% Rabatt auf alles",
               "CHFR":"15% de réduction supplémentaire sur tout",
               "CZ":"Extra sleva 15 % na vše",
               "DE":"Extra 15% Rabatt auf alles",
               "DK":"Ekstra 15% rabat på alt",
               "ES":"15% de descuento adicional",
               "FI":"Saa 15% lisäalennus kaikesta ",
               "FR":"15% de réduction supplémentaire sur tout",
               "HU":"További 15% kedvezményt adunk",
               "IT":"15% di Sconto Aggiuntivo",
               "NL":"Krijg 15% extra korting op alles",
               "NO":"Ytterligere 15% rabatt på alt",
               "PL":"Dodatkowe 15% rabatu ",
               "PT":"15% de desconto adicional",
               "SE":"Ytterligare 15% rabatt på allt",
               "SK":"Extra zľava 15 % na všetko",
               "UK":"Additional 15% off everything "
            },
            "e14e60a1-da3d-413f-a540-3909aab3e450":{
               "AT":"bei jedem Einkauf über 250 € ",
               "CHDE":"bei jedem Einkauf über 250 € ",
               "CHFR":"à partir de 250 € d'achat",
               "CZ":"při nákupu nad 6 200 Kč",
               "DE":"bei jedem Einkauf über 250 € ",
               "DK":"når du køber for min. 1.850 kr.",
               "ES":"realizando un pedido mínimo de 250 €",
               "FI":"tilatessasi vähintään 250 € edestä.",
               "FR":"à partir de 250 € d'achat",
               "HU":"min. 100 000 Ft értékű vásárlás esetén.",
               "IT":"su ogni acquisto a partire da 250 €",
               "NL":"bei jedem Einkauf über 250 € ",
               "NO":"når du handler for minimum 3 000 kr. ",
               "PL":"przy zakupach za min. 1 500 zł",
               "PT":"em compras no valor mínimo de 250 €",
               "SE":"när du spenderar över 2 500 kr",
               "SK":"pri nákupe nad 250 €.",
               "UK":" when you spend min. £220"
            },
            "acc1a8b7-4639-44b5-92fd-1734e9a05a0c":{
               "AT":"bei jedem Einkauf über 500 € ",
               "CHDE":"bei jedem Einkauf über 500 € ",
               "CHFR":"à partir de 500 € d'achat",
               "CZ":"při nákupu nad 12 500 Kč",
               "DE":"bei jedem Einkauf über 500 € ",
               "DK":"når du køber for min. 3.700 kr.",
               "ES":"realizando un pedido mínimo de 500 €",
               "FI":"tilatessasi vähintään 500 € edestä.",
               "FR":"à partir de 500 € d'achat",
               "HU":"min. 200 000 Ft értékű vásárlás esetén.",
               "IT":"su ogni acquisto a partire da 500 €",
               "NL":"Wanneer je voor tenminste € 500 koopt.",
               "NO":"når du handler for minimum 5 900 kr. ",
               "PL":"przy zakupach za min. 2 300 zł",
               "PT":"em compras no valor mínimo de 500 €",
               "SE":"när du spenderar över 5 000 kr",
               "SK":"pri nákupe nad 500 €.",
               "UK":"when you spend min. £450"
            },
            "a302bf38-ca03-403d-876c-29c66342cf88":{
               "AT":"bei jedem Einkauf über 1000 € ",
               "CHDE":"bei jedem Einkauf über 1000 € ",
               "CHFR":"à partir de 1000 € d'achat",
               "CZ":"při nákupu nad 25 000 Kč",
               "DE":"bei jedem Einkauf über 1000 € ",
               "DK":"når du køber for min. 7.400 kr.",
               "ES":"realizando un pedido mínimo de 1.000 €",
               "FI":"tilatessasi vähintään 1 000 € edestä.",
               "FR":"à partir de 1000 € d'achat",
               "HU":"min. 280 000 Ft értékű vásárlás esetén.",
               "IT":"su ogni acquisto a partire da 1000 €",
               "NL":"Wanneer je voor tenminste € 1000 koopt.",
               "NO":"når du handler for minimum 11 700 kr. ",
               "PL":"przy zakupach za min. 4 500 zł",
               "PT":"em compras no valor mínimo de 1000 €",
               "SE":"när du spenderar över 10 000 kr",
               "SK":"pri nákupe nad 1 000 €.",
               "UK":"when you spend min. £900"
            }
         },
         "0e7fc5b4-cf0c-4470-8e16-251d3bfefe99":{
            "09dfc18c-fa4d-406f-aff2-0973f9ae6627":{
               "AT":"bei jedem Einkauf über 250 € ",
               "CHDE":"bei jedem Einkauf über 250 € ",
               "CHFR":"à partir de 250 € d'achat",
               "CZ":"při nákupu nad 6 200 Kč",
               "DE":"bei jedem Einkauf über 250 € ",
               "DK":"når du køber for min. 1.850 kr.",
               "ES":"realizando un pedido mínimo de 250 €",
               "FI":"tilatessasi vähintään 250 € edestä.",
               "FR":"à partir de 250 € d'achat",
               "HU":"min. 100 000 Ft értékű vásárlás esetén.",
               "IT":"su ogni acquisto a partire da 250 €",
               "NL":"bei jedem Einkauf über 250 € ",
               "NO":"når du handler for minimum 3 000 kr. ",
               "PL":"przy zakupach za min. 1 500 zł",
               "PT":"em compras no valor mínimo de 250 €",
               "SE":"när du spenderar över 2 500 kr",
               "SK":"pri nákupe nad 250 €.",
               "UK":" when you spend min. £220"
            }
         },
         "0e780e86-4b23-4f19-838b-0cc201b0f28a":{
            "66f9a8f3-25db-49ef-8310-1056dd9a380a":{
               "AT":"#ff0000",
               "CHDE":"#ffccb7",
               "CHFR":"#ffccb7",
               "CHIT":"#ffccb7",
               "CZ":"#ffccb7",
               "DE":"#0000ff",
               "DK":"#ffccb7",
               "ES":"#ffccb7",
               "FI":"#ffccb7",
               "FR":"#ffccb7",
               "HU":"#ffccb7",
               "IT":"#ffccb7",
               "NL":"#ffccb7",
               "NO":"#ffccb7",
               "PL":"#00ff00",
               "PT":"#ffccb7",
               "SE":"#ffccb7",
               "SK":"#ffccb7",
               "UK":"#ff0000"
            }
         }
      },
      "template_id":"1d2228ae-dca3-41dc-a0ef-b5f737919c6e",
      "css":".title-advantages {\n            text-align: center;\n            font-size: 11px;\n            color: #8c8278;\n            padding-bottom: 10px;\n            padding-top: 10px;\n            margin: 0;\n          }\n          \n          .title-advantages-item {\n            margin-left: 4px;\n          }\n          \n          .newsletterRecommendationHeader {\n            text-align: center;\n            font-size: 11px;\n            color: #8c8278;\n            margin-bottom: 10px;\n            margin-top: 10px;\n          }\n          \n          /* NEWSLETTER START */\n          \n          .newsletterFreebieContainer {\n            padding-left: 10px;\n          }\n          \n          .newsletterBottom80px {\n            padding-bottom: 80px;\n          }\n\n          .newsletterBottom60px {\n            padding-bottom: 60px;\n          }\n          \n          .newsletterContainer {\n            padding-left: 20px;\n            padding-right: 20px;\n          }\n          \n          .newsletterCta {\n            font-size: 20px;\n            line-height: 1.25;\n            font-family: \"Open Sans\", sans-serif;\n          }\n          \n          .newsletterBottom20px {\n            padding-bottom: 20px;\n          }\n          \n          .newsletterBottom35px {\n            padding-bottom: 35px;\n          }\n          \n          .newsletterParagraph {\n            font-size: 18px;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n          }\n          \n          .newsletterTitleNew {\n            font-size: 30px;\n            font-weight: 400;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n          }\n          \n          .newsletterTitle {\n            font-size: 30px;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n          }\n          \n          .newsletterProductTitle {\n            font-size: 20px;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n          }\n          \n          .newsletterProductLowPrice {\n            font-size: 18px;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n            font-weight: 600;\n          }\n          \n          .newsletterProductHightPrice {\n            font-size: 14px;\n            font-family: \"Open Sans\", sans-serif;\n            line-height: 1.25;\n            text-decoration: line-through;\n          }\n          \n          .newsletterRight10px {\n            padding-right: 10px;\n          }\n          \n          .newsletterLeft10px {\n            padding-left: 10px;\n          }\n          \n          /* NEWSLETTER END */\n          \n          .newsletterFooter {\n            padding-left: 20px !important;\n            padding-right: 20px !important;\n          }\n          \n          .newsletterConditions {\n            color: black;\n            font-family: \"Open Sans\", sans-serif;\n            font-size: 8px;\n          }\n          \n          .newsletterFooterCompanyDetails {\n            vertical-align: middle;\n            padding-top: 20px;\n            padding-right: 0px;\n            padding-bottom: 20px;\n            font-size: 11px;\n            font-family: \"Open Sans\", sans-serif !important;\n            color: #000000;\n            background: #ececec;\n            width: 100%;\n          }\n          \n          .newsletterFooterTitle {\n            text-align: left;\n            color: #000000;\n            font-family: \"Open Sans\", sans-serif;\n            font-size: 20px;\n          }\n          \n          .newsletterProductTitleFreebie {\n            text-align: center;\n            color: #000000;\n            font-family: \"Open Sans\", sans-serif;\n            font-size: 20px;\n          }\n          \n          .newsletterFooterCategoryLEFT {\n            padding-bottom: 20px !important;\n            padding-right: 10px !important;\n          }\n          \n          .newsletterFooterCategoryRIGHT {\n            padding-bottom: 20px !important;\n            padding-left: 10px !important;\n          }\n          \n          .newsletterFooterCategoryLEFTBottom {\n            padding-right: 10px !important;\n          }\n          \n          .newsletterFooterCategoryRIGHTBottom {\n            padding-left: 10px !important;\n          }\n          \n          .newsletterSocialIcon {\n            padding-left: 25px !important;\n          }\n          \n          .newsletterTopBottomContainer {\n            padding-top: 35px !important;\n            padding-bottom: 35px !important;\n          }\n          \n          .newsletterKlarnaBannerContainer {\n            padding-top: 35px !important;\n            padding-bottom: 35px !important;\n          }\n          \n          .newsletterSoonEndingTitle {\n            color: #000000;\n            font-family: \"Open Sans\", sans-serif;\n            font-size: 20px;\n          }\n          \n          @media screen and (max-width: 768px) {\n            .newsletterFooterCategoryLEFTBottom {\n              padding-right: 5px !important;\n            }\n          \n            .newsletterFooterCategoryRIGHTBottom {\n              padding-left: 5px !important;\n            }\n          \n            .newsletterFooterCategoryLEFT {\n              padding-bottom: 10px !important;\n              padding-right: 5px !important;\n            }\n          \n            .newsletterFooterCategoryRIGHT {\n              padding-bottom: 10px !important;\n              padding-left: 5px !important;\n            }\n          \n            .newsletterSocialIcon {\n              padding-left: 13px !important;\n            }\n          \n            .newsletterTopBottomContainer {\n              padding-top: 20px !important;\n              padding-bottom: 20px !important;\n            }\n          \n            .newsletterFooterTitle {\n              font-size: 18px;\n            }\n          \n            .newsletterProductTitleFreebie {\n              font-size: 18px;\n            }\n          \n            .newsletterProductTitle {\n              font-size: 18px;\n            }\n          \n            .newsletterProductLowPrice {\n              font-size: 16px;\n            }\n          \n            .newsletterProductHightPrice {\n              display: block;\n            }\n          \n            .newsletterProductTitleContainer {\n              padding-top: 10px;\n            }\n          \n            .newsletterTitle {\n              font-size: 25px;\n            }\n          \n            .newsletterTitleNew {\n              font-size: 20px;\n            }\n          \n            .newsletterContainer {\n              padding-left: 10px;\n              padding-right: 10px;\n            }\n          \n            .newsletterFreebieContainer {\n              padding-left: 10px;\n              padding-right: 0px !important;\n            }\n          \n            .newsletterBottom35px {\n              padding-bottom: 20px;\n            }\n          \n            .newsletterParagraph {\n              font-size: 16px;\n            }\n          \n            .newsletterLeft10px {\n              padding-left: 5px;\n            }\n          \n            .newsletterRight10px {\n              padding-right: 5px;\n            }\n          \n            .newsletterBottom20px {\n              padding-bottom: 10px;\n            }\n          \n            .newsletterBottom80px {\n              padding-bottom: 50px;\n            }\n\n            .newsletterBottom60px {\n              padding-bottom: 40px;\n            }\n          }\n          \n          @media screen and (max-width: 570px) {\n            .newsletterProductTitleFreebie {\n              font-size: 16px;\n            }\n          }\n          \n          @media screen and (max-width: 460px) {\n            .newsletterProductTitleFreebie {\n              font-size: 14px;\n            }\n          }\n          \n          @media screen and (max-width: 370px) {\n            .newsletterProductTitleFreebie {\n              font-size: 12px;\n            }\n          }",
      "layout":[
         {
            "id":"24bcc96d-915f-45a4-b2a5-1ca4f0c7bc13",
            "order":1,
            "is_active":true,
            "renderOn":{
               "AT":true,
               "CHDE":true,
               "CHFR":true,
               "CZ":true,
               "DE":true,
               "DK":true,
               "ES":true,
               "FI":true,
               "FR":true,
               "HU":true,
               "IT":true,
               "NL":true,
               "NO":true,
               "PL":true,
               "PT":true,
               "SE":true,
               "SK":true,
               "UK":true
            },
            "section_id":"22281359-e66b-4fbf-b1ce-678baa9765f0"
         },
         {
            "id":"6dac4f88-a11d-4aaf-a6a1-866705a09a50",
            "order":0,
            "is_active":true,
            "renderOn":{
               "AT":true,
               "CHDE":true,
               "CHFR":true,
               "CZ":true,
               "DE":true,
               "DK":true,
               "ES":true,
               "FI":true,
               "FR":true,
               "HU":true,
               "IT":true,
               "NL":true,
               "NO":true,
               "PL":true,
               "PT":true,
               "SE":true,
               "SK":true,
               "UK":true
            },
            "section_id":"b0633072-f939-4fbe-a4a0-ea602729cf82"
         },
         {
            "id":"a2f0b50c-7760-410d-be83-b4f95e26dfc1",
            "section_id":"0e7fc5b4-cf0c-4470-8e16-251d3bfefe99",
            "order":2,
            "is_active":true,
            "renderOn":{
               "AT":true,
               "CHDE":true,
               "CHFR":true,
               "CZ":true,
               "DE":true,
               "DK":true,
               "ES":true,
               "FI":true,
               "FR":true,
               "HU":true,
               "IT":true,
               "NL":true,
               "NO":true,
               "PL":true,
               "PT":true,
               "SE":true,
               "SK":true,
               "UK":true
            }
         },
         {
            "id":"4e047394-c250-40ad-981b-210679486964",
            "section_id":"0e780e86-4b23-4f19-838b-0cc201b0f28a",
            "order":3,
            "is_active":true,
            "renderOn":{
               "AT":true,
               "CHDE":true,
               "CHFR":true,
               "CZ":true,
               "DE":true,
               "DK":true,
               "ES":true,
               "FI":true,
               "FR":true,
               "HU":true,
               "IT":true,
               "NL":true,
               "NO":true,
               "PL":true,
               "PT":true,
               "SE":true,
               "SK":true,
               "UK":true
            }
         }
      ],
      "id":"e25ff844-33f7-4337-90bb-614caa5ab0c9"
   }
]