name: Build and Test CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
      - run: npm install
      - name: Build app
      - run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install and run test cases
      - run: npm install
      - run: npm test
