name: Build and Publicate to GH Pages
on: [push]
jobs:
  build:
    runs-on: macos
    steps:
      - name: Check Repo
        uses: actions/checkout@v3
        with:
          version: 1
      - name: Install dependencies
        run: |
            npm install
            npm run build
      - name: Push Repo
        run: |
          git add .
          git commit -m "Build project"
          git push
